name: CLIforSQL
on:
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          ip=$(curl ipinfo.io/ip)
          az sql server firewall-rule create -g rg-nabeel --server test-nabeelsql --name ADO-Deploy --start-ip-address $ip --end-ip-address $ip
          az account show
          az sql db import --name test-nabeeldb2--server test-nabeelsql --resource-group rg-nabeel --admin-user nabeel.zaidi@opticca.com --admin-password Amity@4492 --storage-key-type StorageAccessKey --storage-key /UgeH40HoDrKuld/kDk6EN0o9vrLhCoVLr+DzZBF30g8XfUNcq6/q0iPxi955DloT3sPNyDczK8x+AStbc1bhg== --storage-uri https://testnabeelstorage.blob.core.windows.net/testbacpac/WideWorldImporters-Standard.bacpac
          az sql server firewall-rule delete -g rg-nabeel --server test-nabeelsql --name ADO-Deploy
# az storage -h

# jobs:
#   Read_yaml:
#     name: get-variable
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: CumulusDS/get-yaml-paths-action@v0.1.0
#         id: yaml-data
#         with:
#           file: ./ls.infrastructure/Pulumi.ls.yaml
#           bar: config.azure-native:KeyvaultSecretName
#       - name: Display read-yaml output
#         run: echo "${{ steps.yaml-data.outputs.bar }}"
