name: Read-Yaml
on:
  workflow_dispatch:
  
jobs:
  Read_yaml:
    name: get-variable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CumulusDS/get-yaml-paths-action@v0.1.0
        id: yaml-data
        with:
          file: ./ls.infrastructure/file.yml
          bar: foo.bar
          providerStage: provider.stage
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.bar }}"
